/**
 * Builds a minimal valid DOCX buffer containing a "Redline Summary" document.
 * Used for PDFs (which have no editable XML) and as a fallback.
 * The output contains real <w:del> and <w:ins> tracked-change markup.
 */
export function buildRedlineSummaryDocx(
  originalFilename: string,
  edits: Array<{ originalText: string; replacementText: string; instruction: string; reason?: string | null }>
): Buffer {
  const author = "Legal Contract Analyzer";
  const ts = new Date().toISOString();

  // Build change paragraphs XML
  let changeParas = "";
  edits.forEach((edit, i) => {
    const revDel = 2000 + i * 2;
    const revIns = 2001 + i * 2;

    changeParas += `
    <w:p>
      <w:pPr><w:pStyle w:val="Heading2"/></w:pPr>
      <w:r><w:t xml:space="preserve">Change ${i + 1}: ${escapeXml(edit.instruction)}</w:t></w:r>
    </w:p>
    <w:p>
      <w:pPr><w:jc w:val="left"/></w:pPr>
      <w:del w:id="${revDel}" w:author="${escapeXml(author)}" w:date="${ts}">
        <w:r>
          <w:rPr><w:color w:val="FF0000"/></w:rPr>
          <w:delText xml:space="preserve">${escapeXml(edit.originalText)}</w:delText>
        </w:r>
      </w:del>
      <w:ins w:id="${revIns}" w:author="${escapeXml(author)}" w:date="${ts}">
        <w:r>
          <w:rPr><w:color w:val="00AA00"/></w:rPr>
          <w:t xml:space="preserve">${escapeXml(edit.replacementText)}</w:t>
        </w:r>
      </w:ins>
    </w:p>
    ${edit.reason ? `<w:p><w:r><w:rPr><w:i/><w:color w:val="555555"/></w:rPr><w:t xml:space="preserve">Reason: ${escapeXml(edit.reason)}</w:t></w:r></w:p>` : ""}
    <w:p/>`;
  });

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas"
  xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink"
  xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:oel="http://schemas.microsoft.com/office/2019/extlst"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"
  xmlns:v="urn:schemas-microsoft-com:vml"
  xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing"
  xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
  xmlns:w10="urn:schemas-microsoft-com:office:word"
  xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
  xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"
  xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml"
  xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex"
  xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid"
  xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml"
  xmlns:w16sdtdh="http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash"
  xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex"
  xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup"
  xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk"
  xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"
  xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape"
  mc:Ignorable="w14 w15 w16se w16cid w16 w16cex w16sdtdh wp14">
  <w:body>
    <w:p>
      <w:pPr><w:pStyle w:val="Title"/></w:pPr>
      <w:r><w:t>Redlined Document</w:t></w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:rPr><w:color w:val="777777"/><w:sz w:val="20"/></w:rPr>
        <w:t xml:space="preserve">Source: ${escapeXml(originalFilename)} — Generated by Legal Contract Analyzer</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:rPr><w:color w:val="777777"/><w:sz w:val="20"/></w:rPr>
        <w:t xml:space="preserve">Date: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</w:t>
      </w:r>
    </w:p>
    <w:p/>
    ${changeParas}
    <w:sectPr/>
  </w:body>
</w:document>`;

  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`;

  const rels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

  const wordRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
</Relationships>`;

  const AdmZip = require("adm-zip");
  const zip = new AdmZip();
  zip.addFile("[Content_Types].xml", Buffer.from(contentTypes, "utf8"));
  zip.addFile("_rels/.rels", Buffer.from(rels, "utf8"));
  zip.addFile("word/document.xml", Buffer.from(documentXml, "utf8"));
  zip.addFile("word/_rels/document.xml.rels", Buffer.from(wordRels, "utf8"));

  return zip.toBuffer();
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
